name: Deployment

on:
  push:
    branches: [ master ]

jobs:
  deploy-staging:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: vite-app
    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_STAGING_BUCKET_NAME}}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        
  deploy-production:
     needs: [deploy-staging]
     runs-on: ubuntu-latest

     strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

     steps:
     - name: Download artifact
       uses: actions/download-artifact@v2
       with:
        name: vite-app
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
         AWS_S3_BUCKET: AWS_PRODUCTION_BUCKET_NAME
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_REGION:  AWS_REGION
         
   
