name: Deployment

on:
  push:
    branches: [ master ]

jobs:
  deploy-staging:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
      environment: staging
      url: 'http://jennycj-react-vite-app.s3-website.us-east-2.amazonaws.com'
      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_STAGING_BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SOURCE_DIR: "build"
        
  deploy-production:
     needs: [deploy-staging]
     runs-on: ubuntu-latest

     strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

     steps:
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        environment: staging
        url: 'http://prod-react-vite-app.s3-website.us-east-2.amazonaws.com'
        with:
          args: --acl public-read --delete
        env:
         AWS_S3_BUCKET: ${{ secrets.AWS_PRODUCTION_BUCKET_NAME }}
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_REGION: ${{ secrets.AWS_REGION }}
         SOURCE_DIR: "build"
   
